### ISSUE TITLE
Model download link is broken

### ISSUE THREAD

**Issue by mjafari-1qb** [google-research/big_transfer#24]
It seems BiT-S .h5 model download links are not working:
https://storage.googleapis.com/bit_models/BiT-S-R50x1.h5
https://storage.googleapis.com/bit_models/BiT-S-R100x1.h5
https://storage.googleapis.com/bit_models/BiT-S-R50x3.h5
https://storage.googleapis.com/bit_models/BiT-S-R101x3.h5
https://storage.googleapis.com/bit_models/BiT-S-R152x4.h5

**Comment by jessicayung** [comment]
Hello, these should now work. Thanks for raising the issue!

**Comment by mjafari-1qb** [comment]
Thank you very much!

Just it seems the R100x1 is not yet fixed:
https://storage.googleapis.com/bit_models/BiT-S-R100x1.h5

**Comment by mohammadhj** [comment]
Also I think R50x1 and R50x3 files are the same and have the same size:
https://storage.googleapis.com/bit_models/BiT-S-R50x1.h5
https://storage.googleapis.com/bit_models/BiT-S-R50x3.h5

**Comment by jessicayung** [comment]
Thanks - we are looking into the h5 files for BiT-S and will let you know when we have checked them.
